backend:
  name: git-gateway
  branch: master
media_folder: source/images
public_folder: /images
enable: true
admin_path: admin
collections:
  - name: posts
    label: 文章
    folder: source/_posts
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - label: 标题
        name: title
        widget: string
      - label: 日期
        name: date
        widget: datetime
        dateFormat: YYYY-MM-DD
        timeFormat: HH:mm:ss
        format: YYYY-MM-DD HH:mm:ss
      - label: 分类
        name: categories
        widget: list
      - label: 标签
        name: tags
        widget: list
      - label: 正文
        name: body
        widget: markdown
  - name: all_posts
    fields: &ref_0
      - label: Title
        name: title
        widget: string
      - label: Publish Date
        name: date
        widget: datetime
        dateFormat: YYYY-MM-DD
        timeFormat: HH:mm:ss
        format: YYYY-MM-DD HH:mm:ss
        required: false
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Categories
        name: categories
        widget: list
        required: false
      - label: Body
        name: body
        widget: markdown
        required: false
      - label: Permalink
        name: permalink
        widget: string
        required: false
      - label: Comments
        name: comments
        widget: boolean
        default: true
        required: false
    label: Post
    folder: source/_posts
    create: true
    editor:
      preview: true
  - label: Page
    name: pages
    delete: false
    files:
      - name: admin-index.html
        label: ''
        file: source\admin\index.html
        editor:
          preview: true
        fields: *ref_0
